name: deploy

on:
    push:
        branches:
            - main

jobs:
    tag:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: "0"

            - name: Bump version and push tag
              id: tag
              uses: anothrNick/github-tag-action@v1
              env:
                  WITH_V: true
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  DEFAULT_BUMP: none
                  RELEASE_BRANCHES: main

        outputs:
            bump: ${{ steps.tag.outputs.part }}
            new_tag: ${{ steps.tag.outputs.new_tag }}

    build_release:
        runs-on: ubuntu-latest
        if: needs.tag.outputs.bump != 'none'
        permissions:
            contents: write
        needs: tag
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Install JQ
              run: sudo apt-get install -y jq

            - name: Install pnpm
              uses: pnpm/action-setup@v3
              with:
                  version: 9

            - name: Bump composer.json version
              if: needs.tag.outputs.bump
              run: |
                  VERSION="${{ needs.tag.outputs.new_tag }}"
                  jq ".version=\"${VERSION:1}\"" ./composer.json > ./composer.tmp.json --tab
                  mv ./composer.tmp.json ./composer.json

            - name: Install Node
              uses: actions/setup-node@v4
              with:
                  node-version: "20"
                  cache: "pnpm"

            - name: Install dependencies
              run: pnpm install

            - name: Build artefacts
              run: npm run prod

            - name: Process changelog
              id: changelog_file
              run: |
                  if [[ ! -z $(cat changelog/next.md) ]] ; then
                    echo "changelog=${{ needs.tag.outputs.new_tag }}-$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
                    mv changelog/next.md changelog/${{ needs.tag.outputs.new_tag }}-$(date +'%Y-%m-%d').md
                    touch changelog/next.md
                  else
                    echo "changelog=next" >> $GITHUB_OUTPUT
                  fi

            - name: Create ZIP for release
              run: zip -r adminui-xero-oauth2.zip . -x "*.DS_Store*" -x ".npmrc" -x "./*.config.js" -x "*node_modules*" -x ".github/*" -x ".git/*" -x ".gitignore" -x "./resources/*"

            - name: Commit changes to composer.json version and changelog folder
              continue-on-error: true
              run: |
                  git config --global user.email  "github@evomark.co.uk"
                  git config --global user.name  "AdminUI Action"
                  git add .
                  git commit -m "Github Action compiled resources"
                  git push

            - name: Create Github release
              id: create_release
              uses: softprops/action-gh-release@v2
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  tag_name: ${{ needs.tag.outputs.new_tag }}
                  name: Release ${{ needs.tag.outputs.new_tag }}
                  body_path: changelog/${{ steps.changelog_file.outputs.changelog }}.md
                  draft: false
                  prerelease: false
                  files: adminui-xero-oauth2.zip
